DROP DATABASE IF EXISTS BRAZUKAS;

CREATE DATABASE BRAZUKAS;

USE BRAZUKAS;

#Tabela produto Criacao
CREATE TABLE `PRODUTO` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NOME` varchar(150) NOT NULL,
  `DESCRICAO` text NOT NULL,
  `QUALIDADE` float NOT NULL,
  `CATEGORIA` varchar(50) NOT NULL,
  `STATUS` char(1) NOT NULL,
  `PRECO` decimal(10,2) NOT NULL,
  `PLATAFORMA` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=65 DEFAULT CHARSET=latin1;


#tabela Estoque Criacao
CREATE TABLE `ESTOQUE` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `ID_PRODUTO_FK` int(11) NOT NULL,
  `QUANTIDADE` int(11) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_PRODUTO` (`ID_PRODUTO_FK`),
  CONSTRAINT `FK_PRODUTO` FOREIGN KEY (`ID_PRODUTO_FK`) REFERENCES `PRODUTO` (`ID`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=66 DEFAULT CHARSET=latin1;

#tabela usuario
CREATE TABLE `USUARIO` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NOME` varchar(50) NOT NULL,
  `CPF` varchar(11) DEFAULT NULL,
  `SEXO` char(1) DEFAULT NULL,
  `DATANASCIMENTO` varchar(20) DEFAULT NULL,
  `EMAIL` varchar(50) DEFAULT NULL,
  `PASSWORD` varchar(200) NOT NULL,
  `PERMISSAO` varchar(10) NOT NULL,
  `TOKEN` varchar(20) DEFAULT NULL,
  `STATUS` char(1) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `CPF` (`CPF`),
  UNIQUE KEY `EMAIL_UNIQUE` (`EMAIL`)
) ENGINE=InnoDB AUTO_INCREMENT=68 DEFAULT CHARSET=latin1;

CREATE TABLE `CLIENTE_ENDERECO` (
  `ID_CLIENTE_FK` int(11) NOT NULL,
  `CEP` varchar(14) DEFAULT NULL,
  `LOGRADOURO` varchar(255) DEFAULT NULL,
  `BAIRRO` varchar(255) DEFAULT NULL,
  `NUMERO` int(11) DEFAULT NULL,
  `COMPLEMENTO` varchar(45) DEFAULT NULL,
  `CIDADE` varchar(100) DEFAULT NULL,
  `ESTADO` varchar(100) DEFAULT NULL,
  KEY `FK_ENDERECO_idx` (`ID_CLIENTE_FK`),
  CONSTRAINT `FK_ENDERECO` FOREIGN KEY (`ID_CLIENTE_FK`) REFERENCES `USUARIO` (`ID`) ON DELETE CASCADE ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `CLIENTE_TELEFONE` (
  `ID_CLIENTE_FK` int(11) NOT NULL,
  `TELEFONE` varchar(15) DEFAULT NULL,
  KEY `FK_TELEFONE_idx` (`ID_CLIENTE_FK`),
  CONSTRAINT `FK_TELEFONE` FOREIGN KEY (`ID_CLIENTE_FK`) REFERENCES `USUARIO` (`ID`) ON DELETE CASCADE ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


CREATE TABLE `VENDA` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `DATA_VENDA` varchar(10) NOT NULL,
  `COD_CLIENTE` int(10) NOT NULL,
  `QUANTIDADE` int(10) NOT NULL,
  `DESCONTO` decimal(10,2) DEFAULT NULL,
  `VALOR_TOTAL` decimal(10,2) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1;


CREATE TABLE `VENDA_HAS_PRODUTO` (
  `ID_VENDA_FK` int(11) NOT NULL,
  `ID_PRODUTO_FK` int(11) NOT NULL,
  `VALOR` float NOT NULL,
  `QUANTIDADE` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DELIMITER $$
CREATE TRIGGER atualiza_estoque AFTER INSERT ON VENDA_HAS_PRODUTO FOR EACH ROW
BEGIN
UPDATE ESTOQUE SET QUANTIDADE = QUANTIDADE - NEW.QUANTIDADE WHERE ID_PRODUTO_FK = NEW.ID_PRODUTO_FK;
END $$

CREATE TABLE `TOKENS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `TOKEN` varchar(20) NOT NULL,
  `DATE_EXPIRED` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


CREATE TABLE `IMAGENS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CAMINHO` varchar(255) DEFAULT NULL,
  `ID_PRODUTO_FK` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_IMAGEM_idx` (`ID_PRODUTO_FK`),
  CONSTRAINT `FK_IMAGEM` FOREIGN KEY (`ID_PRODUTO_FK`) REFERENCES `PRODUTO` (`ID`) ON DELETE CASCADE ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `CARRINHO` (
  `ID_CLIENTE` int(11) NOT NULL,
  `ID_PRODUTO` int(11) NOT NULL,
  `STATUS` varchar(20) DEFAULT NULL,
  `QUANTIDADE` int(11) DEFAULT NULL,
  `VALOR` decimal(10,2) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


DROP EVENT IF EXISTS limparTokens;

SET GLOBAL event_scheduler = ON;

CREATE EVENT limparTokens
ON SCHEDULE EVERY 1 MINUTE
ON COMPLETION PRESERVE
DO
     DELETE FROM BRAZUKAS.TOKENS
	WHERE 1=1
	and DATE_EXPIRED <= now() OR DATE_EXPIRED is null;

INSERT INTO `BRAZUKAS`.`USUARIO` (`ID`, `NOME`, `CPF`, `SEXO`, `DATANASCIMENTO`, `EMAIL`, `PASSWORD`, `PERMISSAO`, `STATUS`) VALUES ('1', 'Admin', '11111111111', 'M', '01/01/1998', 'admin@admin.com', '21232f297a57a5a743894a0e4a801fc3', 'ADMIN', 'A');


CREATE TABLE `BRAZUKAS`.`CLIENTE_PAGAMENTO` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NAME_CART` VARCHAR(255) NULL,
  `NUMBER_CART` CHAR(16) NULL,
  `VALID_THRU` CHAR(5) NULL,
  `SECURITY_CODE` CHAR(3) NULL,
  `ID_CLIENTE_FK` INT NULL,
  PRIMARY KEY (`ID`),
  INDEX `ID_CLIENTE_FK_idx` (`ID_CLIENTE_FK` ASC),
  CONSTRAINT `ID_CLIENTE_FK`
    FOREIGN KEY (`ID_CLIENTE_FK`)
    REFERENCES `BRAZUKAS`.`USUARIO` (`ID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION);




