DROP DATABASE IF EXISTS BRAZUKAS;

CREATE DATABASE BRAZUKAS;

USE BRAZUKAS;

#Tabela produto Criacao
CREATE TABLE `PRODUTO` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NOME` varchar(150) NOT NULL,
  `DESCRICAO` text NOT NULL,
  `QUALIDADE` float NOT NULL,
  `CATEGORIA` varchar(50) NOT NULL,
  `STATUS` char(1) NOT NULL,
  `PRECO` decimal(10,2) NOT NULL,
  `PLATAFORMA` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=65 DEFAULT CHARSET=latin1;


#tabela Estoque Criacao
CREATE TABLE `ESTOQUE` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `ID_PRODUTO_FK` int(11) NOT NULL,
  `QUANTIDADE` int(11) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_PRODUTO` (`ID_PRODUTO_FK`),
  CONSTRAINT `FK_PRODUTO` FOREIGN KEY (`ID_PRODUTO_FK`) REFERENCES `PRODUTO` (`ID`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=66 DEFAULT CHARSET=latin1;

#tabela usuario
CREATE TABLE `USUARIO` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NOME` varchar(50) NOT NULL,
  `CPF` varchar(11) DEFAULT NULL,
  `SEXO` char(1) DEFAULT NULL,
  `DATANASCIMENTO` varchar(20) DEFAULT NULL,
  `EMAIL` varchar(50) DEFAULT NULL,
  `PASSWORD` varchar(200) NOT NULL,
  `PERMISSAO` varchar(10) NOT NULL,
  `TOKEN` varchar(20) DEFAULT NULL,
  `STATUS` char(1) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `CPF` (`CPF`),
  UNIQUE KEY `EMAIL_UNIQUE` (`EMAIL`)
) ENGINE=InnoDB AUTO_INCREMENT=68 DEFAULT CHARSET=latin1;


CREATE TABLE `CLIENTE_ENDERECO` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `ID_CLIENTE_FK` int(11) NOT NULL,
  `CEP` varchar(14) DEFAULT NULL,
  `LOGRADOURO` varchar(255) DEFAULT NULL,
  `BAIRRO` varchar(255) DEFAULT NULL,
  `NUMERO` int(11) DEFAULT NULL,
  `COMPLEMENTO` varchar(45) DEFAULT NULL,
  `CIDADE` varchar(100) DEFAULT NULL,
  `ESTADO` varchar(100) DEFAULT NULL,
  `TIPO` char(1) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_ENDERECO_idx` (`ID_CLIENTE_FK`),
  CONSTRAINT `FK_ENDERECO` FOREIGN KEY (`ID_CLIENTE_FK`) REFERENCES `USUARIO` (`ID`) ON DELETE CASCADE ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*
TIPO

E = endereco de entrega
F = endereco faturamento
I = inativo
* = endereco de entrega e faturamento

*/

CREATE TABLE `CLIENTE_TELEFONE` (
  `ID_CLIENTE_FK` int(11) NOT NULL,
  `TELEFONE` varchar(15) DEFAULT NULL,
  KEY `FK_TELEFONE_idx` (`ID_CLIENTE_FK`),
  CONSTRAINT `FK_TELEFONE` FOREIGN KEY (`ID_CLIENTE_FK`) REFERENCES `USUARIO` (`ID`) ON DELETE CASCADE ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


CREATE TABLE `VENDA` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `DATA_VENDA` date NOT NULL,
  `COD_CLIENTE` int(10) NOT NULL,
  `QUANTIDADE` int(10) NOT NULL,
  `VALOR_TOTAL` decimal(10,2) NOT NULL,
  `STATUS` varchar(20) DEFAULT NULL,
  `NUM_PEDIDO` varchar(45) DEFAULT NULL,
  `ID_ENTREGA` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


CREATE TABLE `VENDA_HAS_PRODUTO` (
  `ID_VENDA_FK` int(11) NOT NULL,
  `ID_PRODUTO_FK` int(11) NOT NULL,
  `VALOR` float NOT NULL,
  `QUANTIDADE` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DELIMITER $$
CREATE TRIGGER atualiza_estoque AFTER INSERT ON VENDA_HAS_PRODUTO FOR EACH ROW
BEGIN
UPDATE ESTOQUE SET QUANTIDADE = QUANTIDADE - NEW.QUANTIDADE WHERE ID_PRODUTO_FK = NEW.ID_PRODUTO_FK;
END $$

CREATE TABLE `TOKENS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `TOKEN` varchar(20) NOT NULL,
  `DATE_EXPIRED` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


CREATE TABLE `IMAGENS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CAMINHO` varchar(255) DEFAULT NULL,
  `ID_PRODUTO_FK` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_IMAGEM_idx` (`ID_PRODUTO_FK`),
  CONSTRAINT `FK_IMAGEM` FOREIGN KEY (`ID_PRODUTO_FK`) REFERENCES `PRODUTO` (`ID`) ON DELETE CASCADE ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

 CREATE TABLE `CARRINHO` (
  `ID_CLIENTE` int(11) DEFAULT NULL,
  `ID_PRODUTO` int(11) NOT NULL,
  `STATUS` varchar(20) DEFAULT NULL,
  `QUANTIDADE` int(11) DEFAULT NULL,
  `VALOR` decimal(10,2) DEFAULT NULL,
  `TOKEN_SESSION` char(32) DEFAULT NULL,
  `MOMENT` datetime DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=latin1;



DROP EVENT IF EXISTS limparTokens;

SET GLOBAL event_scheduler = ON;

CREATE EVENT limparTokens
ON SCHEDULE EVERY 1 MINUTE
ON COMPLETION PRESERVE
DO
     DELETE FROM BRAZUKAS.TOKENS
	WHERE 1=1
	and DATE_EXPIRED <= now() OR DATE_EXPIRED is null;

INSERT INTO `BRAZUKAS`.`USUARIO` (`ID`, `NOME`, `CPF`, `SEXO`, `DATANASCIMENTO`, `EMAIL`, `PASSWORD`, `PERMISSAO`, `STATUS`) VALUES ('1', 'Admin', '11111111111', 'M', '01/01/1998', 'admin@admin.com', '21232f297a57a5a743894a0e4a801fc3', 'ADMIN', 'A');


CREATE TABLE `CLIENTE_PAGAMENTO` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME_CART` varchar(255) DEFAULT NULL,
  `NUMBER_CART` char(20) DEFAULT NULL,
  `ID_VENDA_FK` int(11) DEFAULT NULL,
  `VALOR` varchar(20) NOT NULL,
  `QTD_PARCELAS` varchar(45) NOT NULL,
  `PAYPAL_EMAIL` varchar(255) DEFAULT NULL,
  `PAYPAL_CPF` varchar(45) DEFAULT NULL,
  `NUM_BOLETO` varchar(60) DEFAULT NULL,
  `MP_EMAIL` varchar(255) DEFAULT NULL,
  `MP_CPF` varchar(45) DEFAULT NULL,
  `TIPO` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `ID_CLIENTE_FK_idx` (`ID_VENDA_FK`),
  CONSTRAINT `ID_VENDA_FK` FOREIGN KEY (`ID_VENDA_FK`) REFERENCES `VENDA` (`ID`) ON DELETE CASCADE ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1;



CREATE TABLE `FRETES` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `UF` char(2) NOT NULL,
  `VALOR_FAST` double NOT NULL,
  `VALOR_NORMAL` double NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;




INSERT INTO FRETES (ID, UF, VALOR_FAST, VALOR_NORMAL) VALUES ('1','AC','32.99','9.99');
INSERT INTO FRETES (ID, UF, VALOR_FAST, VALOR_NORMAL) VALUES ('2','AL','31.99','9.99');
INSERT INTO FRETES (ID, UF, VALOR_FAST, VALOR_NORMAL) VALUES ('3','AP','32.99','9.99');
INSERT INTO FRETES (ID, UF, VALOR_FAST, VALOR_NORMAL) VALUES ('4','AM','33.99','9.99');
INSERT INTO FRETES (ID, UF, VALOR_FAST, VALOR_NORMAL) VALUES ('5','BA','29.99','9.99');
INSERT INTO FRETES (ID, UF, VALOR_FAST, VALOR_NORMAL) VALUES ('6','CE','28.99','9.99');
INSERT INTO FRETES (ID, UF, VALOR_FAST, VALOR_NORMAL) VALUES ('7','DF','25.99','8.99');
INSERT INTO FRETES (ID, UF, VALOR_FAST, VALOR_NORMAL) VALUES ('8','ES','26.99','8.99');
INSERT INTO FRETES (ID, UF, VALOR_FAST, VALOR_NORMAL) VALUES ('9','GO','29.99','9.99');
INSERT INTO FRETES (ID, UF, VALOR_FAST, VALOR_NORMAL) VALUES ('10','MA','15.99','9.99');
INSERT INTO FRETES (ID, UF, VALOR_FAST, VALOR_NORMAL) VALUES ('11','MT','18.99','10.99');
INSERT INTO FRETES (ID, UF, VALOR_FAST, VALOR_NORMAL) VALUES ('12','MS','19.99','11.99');
INSERT INTO FRETES (ID, UF, VALOR_FAST, VALOR_NORMAL) VALUES ('13','MG','17.99','7.99');
INSERT INTO FRETES (ID, UF, VALOR_FAST, VALOR_NORMAL) VALUES ('14','PA','28.99','9.99');
INSERT INTO FRETES (ID, UF, VALOR_FAST, VALOR_NORMAL) VALUES ('15','PB','29.99','9.99');
INSERT INTO FRETES (ID, UF, VALOR_FAST, VALOR_NORMAL) VALUES ('16','PR','28.99','7.99');
INSERT INTO FRETES (ID, UF, VALOR_FAST, VALOR_NORMAL) VALUES ('17','PE','30.99','9.99');
INSERT INTO FRETES (ID, UF, VALOR_FAST, VALOR_NORMAL) VALUES ('18','PI','25.99','9.99');
INSERT INTO FRETES (ID, UF, VALOR_FAST, VALOR_NORMAL) VALUES ('19','RJ','16.99','5.99');
INSERT INTO FRETES (ID, UF, VALOR_FAST, VALOR_NORMAL) VALUES ('20','RN','34.99','9.99');
INSERT INTO FRETES (ID, UF, VALOR_FAST, VALOR_NORMAL) VALUES ('21','RS','23.99','7.99');
INSERT INTO FRETES (ID, UF, VALOR_FAST, VALOR_NORMAL) VALUES ('22','RO','35.99','9.99');
INSERT INTO FRETES (ID, UF, VALOR_FAST, VALOR_NORMAL) VALUES ('23','RR','38.99','9.99');
INSERT INTO FRETES (ID, UF, VALOR_FAST, VALOR_NORMAL) VALUES ('24','SC','16.99','7.99');
INSERT INTO FRETES (ID, UF, VALOR_FAST, VALOR_NORMAL) VALUES ('25','SP','11.99','3.99');
INSERT INTO FRETES (ID, UF, VALOR_FAST, VALOR_NORMAL) VALUES ('26','SE','27.99','8.99');
INSERT INTO FRETES (ID, UF, VALOR_FAST, VALOR_NORMAL) VALUES ('27','TO','40.99','9.99');


